"""Puertos del bounded context tenant."""
from __future__ import annotations

from typing import Any, Protocol


class ITenantRepository(Protocol):
    async def es_empresa_maestra(self, empresa_id: int) -> bool: ...

    async def validar_acceso(self, empresa_maestra_id: int, empresa_objetivo_id: int) -> None: ...

    async def empresa_esta_operativa(self, empresa_id: int) -> bool: ...

    async def listar_empresas_administradas(
        self, empresa_maestra_id: int, *, solo_activas: bool = True
    ) -> list[Any]: ...

    async def ids_empresas_administradas_activas(self, empresa_maestra_id: int) -> list[int]: ...


class IEmpresaRepository(Protocol):
    async def listar(self, **kwargs: Any) -> tuple[list[Any], int]: ...

    async def obtener_por_id(self, empresa_id: int) -> Any | None: ...

    async def obtener_por_codigo(self, codigo: str) -> Any | None: ...

    async def crear(self, codigo: str, razon_social: str, **kwargs: Any) -> Any: ...

    async def actualizar(self, empresa_id: int, **datos: Any) -> Any | None: ...

    async def eliminar(self, empresa_id: int) -> bool: ...
