-- Obsoleto: recuperación de contraseña por email fuera de alcance.
-- Si la tabla existe, eliminarla con mysql-init/railway_23_cleanup/01_drop_password_reset_token.sql
-- o ejecutar: railway run python scripts/apply_railway_migrations.py --file 23_schema_cleanup.sql
